export const USER_REGISTER_ROUTE = '/register';
export const USER_LOGIN_ROUTE = '/login';
export const HOME_ROUTE = '/';
export const MY_SCHEDULE_ROUTE = '/my-schedule';
export const INSTITUTIONS_ROUTE = '/institutions';
export const INSTITUTIONS_CREATE_ROUTE = '/institutions/new';
export const INSTITUTION_UPDATE_ROUTE = '/institutions/:institutionId/edit';
export const INSTITUTION_ROUTE = '/institutions/:institutionId';
export const INSTITUTION_MEMBERS_ROUTE = '/institutions/:institutionId/members';
export const INSTITUTION_GROUPS_ROUTE = '/institutions/:institutionId/groups';
export const INSTITUTION_COURSES_ROUTE = '/institutions/:institutionId/courses';
export const INSTITUTION_ROOMS_ROUTE = '/institutions/:institutionId/rooms';
export const INSTITUTION_ACTIVITIES_ROUTE = '/institutions/:institutionId/activities';
export const INSTITUTION_SCHEDULES_ROUTE = '/institutions/:institutionId/schedules';
export const INSTITUTION_MY_SCHEDULE_ROUTE = '/institutions/:institutionId/my-schedule';
export const SCHEDULE_VIEW_ROUTE = '/schedules/:scheduleId';
export const COURSE_ROUTE = '/courses/:courseId';
export const GROUP_ROUTE = '/groups/:groupId';
export const ROOM_ROUTE = '/rooms/:roomId';
export const ACTIVITY_ROUTE = '/activities/:activityId';
export const USER_ROUTE = '/users/:memberId';
export const USER_UPDATE_ROUTE = '/users/:memberId/edit';
export const PROFILE_ROUTE = '/profile';

export const institutionRoute = (institutionId: string) => `/institutions/${institutionId}`;
export const institutionUpdateRoute = (institutionId: string) => `/institutions/${institutionId}/edit`;

export const memberRoute = (memberId: string) => `/users/${memberId}`;
export const memberUpdateRoute = (memberId: string) => `/users/${memberId}/edit`;
export const profileRoute = () => '/profile';
export const groupRoute = (groupId: string) => `/groups/${groupId}`;
export const courseRoute = (courseId: string) => `/courses/${courseId}`;
export const roomRoute = (roomId: string) => `/rooms/${roomId}`;
export const activityRoute = (activityId: string) => `/activities/${activityId}`;
export const scheduleRoute = (scheduleId: string) => `/schedules/${scheduleId}`;
export const institutionSchedulesRoute = (institutionId: string) => `/institutions/${institutionId}/schedules`;
export const institutionMyScheduleRoute = (institutionId: string) => `/institutions/${institutionId}/my-schedule`;
