name: odes

services:
  worker:
    cpus: 2.0
    mem_limit: 4g
    memswap_limit: 4g
    environment:
      NUM_SEARCH_WORKERS: "2"

  rabbitmq:
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
